#- "sourceFiles/ZprimeToTT_M1000_W10_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-01.txt:treeMaker/tree:1:1000"
#- "sourceFiles/ZprimeToTT_M1000_W100_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-08.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M1000_W300_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-13.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M1250_W12p5_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-18.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M1250_W125_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-26.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M1250_W375_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-31.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M1500_W15_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-36.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M1500_W150_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-40.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M1500_W450_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-46.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M2000_W20_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-51.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M2000_W200_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-58.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M2000_W600_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-04.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M3000_W30_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-08.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M3000_W300_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-13.txt:treeMaker/tree:1:5000"
#- "sourceFiles/ZprimeToTT_M3000_W900_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-21.txt:treeMaker/tree:1:5000"

samples:
    
    ZprimeToTT_M1000_W10:
        names:
            - "ZprimeToTT_M1000_W10_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2021-07-22_15-56-01"
        weights:
            - 1.0
    
    ZprimeToTT_M2000_W20:
        names:
            - "ZprimeToTT_M2000_W20_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2021-07-22_15-56-51"
        weights:
            - 1.0
    
    ZprimeToTT_M3000_W30:
        names:
            - "ZprimeToTT_M3000_W30_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2021-07-22_15-57-08"
        weights:
            - 1.0
    
    ZprimeToTT_M4000_W40:
        names:
            - "ZprimeToTT_M4000_W40_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2021-07-22_15-57-43"
        weights:
            - 1.0
    
    QCD:
        names:
            #- "QCD_Pt_170to300_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2021-07-22_15-54-05"
            - "QCD_Pt_300to470_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2021-07-22_15-54-11"
            - "QCD_Pt_470to600_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2021-07-22_15-54-16"
            - "QCD_Pt_600to800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2021-07-22_15-54-25"
            - "QCD_Pt_800to1000_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2021-07-22_15-54-32"
            - "QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM:2021-07-22_15-54-41"
            - "QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2021-07-22_15-54-51"
            - "QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2021-07-22_15-55-00"
            - "QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM:2021-07-22_15-55-32"
        weights:
            #- 103300.0
            - 6826.0
            - 552.6
            - 156.6
            - 26.32
            - 7.5
            - 0.6479
            - 0.08715
            - 0.005242

curves:
    -   label: "t^{lep} (Z'_{2 TeV}) vs. QCD"
        sig:
            sample:         "ZprimeToTT_M2000_W20"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 200) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco < 1) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 200) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:    "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/from-Hala_CNN1_5cat_2021-10-02_17-50-33"
                tag:    null
                tree:   "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK15PFPuppi_boost_2_1_sd_0p1_0_1"
        classifier:     "epoch50_0vs2"
        classifiercut:  "{classifier} > {value}"
        color: 2
        linestyle: 1
    
    -   label: "t^{lep} (Z'_{3 TeV}) vs. QCD"
        sig:
            sample:         "ZprimeToTT_M3000_W30"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 200) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco < 1) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 200) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:    "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/from-Hala_CNN1_5cat_2021-10-02_17-50-33"
                tag:    null
                tree:   "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK15PFPuppi_boost_2_1_sd_0p1_0_1"
        classifier:     "epoch50_0vs2"
        classifiercut:  "{classifier} > {value}"
        color: 4
        linestyle: 1
    
    -   label: "t^{lep} (Z'_{4 TeV}) vs. QCD"
        sig:
            sample:         "ZprimeToTT_M4000_W40"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 200) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco < 1) && ({jet}_nearestGenTopIsLeptonic_reco > 0.5)"
        bkg:
            sample:         "QCD"
            tree:           "treeMaker/tree"
            source:         "sourceFiles/{sample}_{tag}.txt"
            weight:         "({jet}_pT_reco > 200) && (abs({jet}_eta_reco) < 2.5) && ({jet}_nConsti_reco >= 3) && ({jet}_nearestGenTopDR_reco > 1)"
        friends:
            -   dir:    "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/classifier_trees/from-Hala_CNN1_5cat_2021-10-02_17-50-33"
                tag:    null
                tree:   "tree"
        vardict:
            jet:        "jet_selectedPatJetsAK15PFPuppi_boost_2_1_sd_0p1_0_1"
        classifier:     "epoch50_0vs2"
        classifiercut:  "{classifier} > {value}"
        color: 6
        linestyle: 1

xtitle: "Signal efficiency"
ytitle: "Background efficiency"
xrange:
    - 0.0
    - 1.0
yrange:
    - 1.0e-6
    - 1.0
logx: false
logy: true
gridx: true
gridy: true
legendpos: "UL"
legendtextsize: 0.045
outfile: "plots/ROCs/test_roc.pdf"
